aiqianfeng/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 不写也可以，直接匹配
    url(r'^axf/', include('axf.urls', namespace='axf'))

]

axf/urls.py
from django.conf.urls import url

from axf import views

urlpatterns = [

    url(r'^home/', views.home, name="home"),
    url(r'^mine/', views.mine, name="mine"),
    url(r'^market/$', views.urlToMarket, name="urlToMarket"),
    url(r'^market/(\d+)/(\d+)/(\d+)', views.market, name="market"),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^login/', views.login, name='login'),
    url(r'^dologin/', views.doLogin, name="doLogin"),
    url(r'^register/', views.register, name='register'),
    url(r'^doregister/', views.doregister, name='doregister'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^checkuser/', views.checkuser, name='checkuser'),
    url(r'^userInfoMod/', views.userInfoMod, name='userInfoMod'),
    url(r'^addtocart/', views.addtocart, name="addtocart"),
    url(r'^changeselect/', views.changeselect, name="changeselect"),
    url(r'^cartgoodssub/', views.cartgoodssub, name="cartgoodssub"),
    url(r'^genorder/', views.genorder, name="genorder"),
    url(r'^pay/(\d+)', views.pay, name="pay"),

]

axf/models.py
from django.db import models


# Create your models here.
# 首页轮播
class Wheel(models.Model):
    name = models.CharField(max_length=100)
    # id
    trackid = models.CharField(max_length=20)
    # 图片的地址
    img = models.CharField(max_length=200)

    # 配置数据库文件
    class Meta:
        db_table = 'axf_wheel'


# 首页导航
class Nav(models.Model):
    img = models.CharField(max_length=150)
    name = models.CharField(max_length=20)
    trackid = models.CharField(max_length=20)

    class Meta:
        db_table = 'axf_nav'


# 第二个轮播

class Mustbuy(models.Model):
    name = models.CharField(max_length=100)
    # id
    trackid = models.CharField(max_length=20)
    # 图片的地址
    img = models.CharField(max_length=200)

    # 配置数据库文件
    class Meta:
        db_table = 'axf_mustbuy'


# shop商店
class Shop(models.Model):
    name = models.CharField(max_length=100)
    # id
    trackid = models.CharField(max_length=20)
    # 图片的地址
    img = models.CharField(max_length=200)

    # 配置数据库文件
    class Meta:
        db_table = 'axf_shop'


# 主页面显示数据
class Mainshow(models.Model):
    trackid = models.CharField(max_length=20)
    name = models.CharField(max_length=100)
    img = models.CharField(max_length=200)
    categoryid = models.CharField(max_length=20)
    brandname = models.CharField(max_length=100)

    img1 = models.CharField(max_length=200)
    childcid1 = models.CharField(max_length=20)
    productid1 = models.CharField(max_length=20)
    longname1 = models.CharField(max_length=100)
    price1 = models.CharField(max_length=20)
    marketprice1 = models.CharField(max_length=20)

    img2 = models.CharField(max_length=200)
    childcid2 = models.CharField(max_length=20)
    productid2 = models.CharField(max_length=20)
    longname2 = models.CharField(max_length=100)
    price2 = models.CharField(max_length=20)
    marketprice2 = models.CharField(max_length=20)

    img3 = models.CharField(max_length=200)
    childcid3 = models.CharField(max_length=20)
    productid3 = models.CharField(max_length=20)
    longname3 = models.CharField(max_length=100)
    price3 = models.CharField(max_length=20)
    marketprice3 = models.CharField(max_length=20)

    class Meta:
        db_table = 'axf_mainshow'


# 闪送模块

# 分类信息
class FoodTypes(models.Model):
    typeid = models.CharField(max_length=20)
    typename = models.CharField(max_length=100)
    childtypenames = models.CharField(max_length=200)
    typesort = models.CharField(max_length=100)

    class Meta:
        db_table = 'axf_foodtypes'


# 商品
class Goods(models.Model):
    productid = models.CharField(max_length=20)
    productimg = models.CharField(max_length=200)
    productname = models.CharField(max_length=100)
    productlongname = models.CharField(max_length=200)
    isxf = models.BooleanField(default=False)
    pmdesc = models.IntegerField(default=0)
    specifics = models.CharField(max_length=20)
    price = models.CharField(max_length=20)
    marketprice = models.CharField(max_length=20)
    categoryid = models.CharField(max_length=20)
    childcid = models.CharField(max_length=20)
    childcidname = models.CharField(max_length=100)
    dealerid = models.CharField(max_length=20)
    storenums = models.CharField(max_length=20)
    productnum = models.CharField(max_length=20)

    class Meta:
        db_table = 'axf_goods'


# 创建用户模型
class User(models.Model):
    # 字段 用户名，密码，头像，邮箱，电话，
    u_name = models.CharField(max_length=20, unique=True)
    u_passwd = models.CharField(max_length=33)
    u_icon = models.ImageField(upload_to='icons')
    u_email = models.CharField(max_length=50)
    u_phone = models.CharField(max_length=20)

    class Meta:
        db_table = 'axf_user'


class Order(models.Model):
    o_user = models.ForeignKey('User')
    #    状态
    o_status = models.IntegerField(default=0)


class Cart(models.Model):
    # 一条购物车数据对应一个用户，一个用户可以对应多条购物车数据
    c_user = models.ForeignKey('User')
    # 一条购物车对应一条商品
    c_goods = models.ForeignKey('Goods')
    # 商品数量
    c_goods_num = models.IntegerField(default=1)

    c_order = models.ForeignKey('Order', null=True, default=None)
    #   此数据是否选中
    c_selected = models.BooleanField(default=True)
    # 划分，此数据属于购物车展示，还是属于订单展示,false代表购物车，true代表属于订单
    c_belong = models.BooleanField(default=False)

axf/views.py
import hashlib

from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
import time
import random
from django.conf import settings
import os
# Create your views here.
from django.urls import reverse

from axf.models import Wheel, Mustbuy, Shop, Mainshow, FoodTypes, Goods, Nav, User, Cart, Order


# 主页

def home(request):
    title = '主页'
    # 查询主页面的数据
    wheels = Wheel.objects.all()
    # 查询导航数据
    navs = Nav.objects.all()
    # 查询第二个轮播数据
    mustbuys = Mustbuy.objects.all()
    # shop商店
    shops = Shop.objects.all()
    shops_more = shops[3:7]
    shops_rec = shops[7:11]
    # 查询mainshow
    mainshows = Mainshow.objects.all()

    context = {
        'wheels': wheels,
        'navs': navs,
        'mustbuys': mustbuys,
        'shops': shops,
        'shops_more': shops_more,
        'shops_rec': shops_rec,
        'mainshows': mainshows,
    }
    return render(request, 'axf/home/home.html', context=context)


# 闪送

def market(request, typeid, childcid, sort_rule):
    title = "闪送超市"
    # 查询所有类型
    foodtypes = FoodTypes.objects.all()

    if childcid == "0":
        goods_list = Goods.objects.filter(categoryid=typeid)
    else:
        # 查询所有商品
        goods_list = Goods.objects.filter(categoryid=typeid).filter(childcid=childcid)
    # 销量升序
    if sort_rule == "1":
        goods_list = goods_list.order_by("productnum")
    # 销量降序
    elif sort_rule == "2":
        goods_list = goods_list.order_by("-productnum")
    # 价格降序
    elif sort_rule == "3":
        goods_list = goods_list.order_by("-price")
    # 价格升序
    elif sort_rule == "4":
        goods_list = goods_list.order_by("price")
    # 综合排序
    else:
        pass

    # 根据typeid将 childtypenames获取出来
    foodtype = FoodTypes.objects.filter(typeid=typeid)

    # 创建一个默认值
    childetypenames = "全部分类:0"
    if len(foodtype) > 0:
        childetypenames = foodtype.first().childtypenames
    # 切割数据
    childtypenamelist = childetypenames.split("#")
    childtypenamelisttran = []
    # print(childtypenamelist)
    # 二次处理数据
    # [[“名称”,"id"],["名称":"id"], ]
    for item in childtypenamelist:
        itemtran = item.split(":")
        childtypenamelisttran.append(itemtran)

    # print(childtypenamelisttran)

    sort_rule_list = [["综合排序", "0"], ["销量升序", "1"], ["销量降序", "2"], ["价格最低", "3"], ["价格最高", "4"]]

    context = {
        "title": title,
        "foodtypes": foodtypes,
        "goods_list": goods_list[0:20],
        "childtypenameslist": childtypenamelisttran,
        "typeid": typeid,
        "childcid": childcid,
        "sort_rule_list": sort_rule_list,
    }
    return render(request, 'axf/market/market.html', context=context)


# 我的

def mine(request):
    # 配置基本信息
    title = '朕'
    usericon = ''
    # 获取session信息,
    username = request.session.get('username')
    # 判断是否登录
    if username == None:
        username = '未登录'
        # 未登录，给一个值，用于记录
        is_login = False
    else:
        is_login = True
        # 把用户名替换到登录那块
        user = User.objects.get(u_name=username)
        # 匹配路径,上传图片
        usericon = "http://127.0.0.1:8000/static/uploadfiles/" + user.u_icon.url

    context = {
        'title': title,
        'is_login': is_login,
        'username': username,
        'usericon': usericon,
    }
    return render(request, 'axf/mine/mine.html', context=context)


# 用户登录页面
def login(request):
    return render(request, 'axf/user/login.html')


# 登录验证
def doLogin(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    """
            两种写法
                1，直接去数据库查询用户名和密码

                2，用用户名去查找，没找到提示用户名不存在
                用户名找到了再去验证密码，
        """
    user = User.objects.filter(u_name=username)
    if len(user) > 0:

        # 因为注册的时候在输入的时候就加密了，所以在登陆的时候需要要给他加密，让两个密码都进行加密比较
        # 比对加密密码，将密码进行hash算法后进行比较，
        # 导入库
        md5 = hashlib.md5()
        # 对密码编码
        md5.update(password.encode('utf-8'))
        # 加算法
        newpassword = md5.hexdigest()

        # u_passwd是model里面的获取密码
        if newpassword == user.first().u_passwd:
            # 密码成功，把用户名提交到登陆后的页面
            request.session['username'] = username
            # 登陆成功，跳转回个人中心
            response = HttpResponseRedirect(reverse('axf:mine'))
            return response
        else:
            return redirect(reverse('axf:login'))
    else:
        return redirect(reverse('axf:login'))


# 退出登录，两种清除方式，清除登录的信息，
def logout(request):
    # 1，用session清除
    del request.session['username']
    response = HttpResponseRedirect(reverse('axf:mine'))

    # ,2，用cookie清除
    # response.delete_cookie('sessionid')
    # response =  HttpResponseRedirect(reverse('axf:mine'))
    return response


# 注册页面
def register(request):
    return render(request, 'axf/user/register.html')


# 执行注册
def doregister(request):
    try:
        # /存储用户信息
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        # 这里要用[]
        icon = request.FILES['icon']
        print(password)

        # 获取摘要
        md5 = hashlib.md5()
        # 将原数据传入进行摘要计算， 元数据需要需要进行二进制格式
        md5.update(password.encode('utf-8'))
        # 获取摘要后的信息   hex 16进制    digest获取摘要输出
        # digest（）获取到的是二进制的输出   hexdigest（） 获取的是16进制输出，16进制可以直接转换成可见字符串
        p = md5.hexdigest()
        print(p)
        password = p

        user = User()
        user.u_name = username
        user.u_passwd = password
        user.u_email = email
        user.u_phone = phone
        user.u_icon = icon
        user.save()
        # 将用户个人信息存储在session里
        request.session['username'] = username
        return redirect(reverse('axf:mine'))

    except Exception as e:
        print('注册失败')
        return HttpResponse('注册失败')


# 检验用户名是否重复
def checkuser(request):
    uname = request.GET.get('uname')
    users = User.objects.filter(u_name=uname)

    if len(users) > 0:
        msg = '用户已存在'
        state = 300
    else:
        msg = '用户名可用'
        state = 200

    data = {'msg': msg, 'state': state}
    return JsonResponse(data)


# 个人信息
def userInfoMod(request):
    return render(request, 'axf/user/userInfoMod.html')


# 重定向闪送
def urlToMarket(request):
    return redirect(reverse("axf:market", args=["104749", "0", "0"]))


def cart(request):
    # 判断是否登录
    username = request.session.get('username')
    # 未登录
    if username == None:
        return redirect(reverse('axf:login'))
    # 已登录
    user = User.objects.get(u_name=username)
    carts = Cart.objects.filter(c_user=user).filter(c_belong=False)

    context = {
        'carts': carts,
    }
    return render(request, 'axf/cart/cart.html', context)


def addtocart(request):
    # 判断用户是否登录
    username = request.session.get('username')
    # 用户未登录
    if username == None:
        # 跳转到登录页面
        return redirect(reverse('axf:login'))
    # 用户已登录，数据添加到登录车
    goods_id = request.GET.get('goodsid')
    # 通过ID将商品添加到商品的的表里
    goods = Goods.objects.get(pk=goods_id)
    # 获取用户登录信息
    user = User.objects.get(u_name=username)

    # 购物车数量增加
    c = Cart.objects.filter(c_user=user).filter(c_goods=goods).filter(c_belong=False)
    if len(c) == 0:
        c = Cart()
    else:
        c = c.first()
        num = c.c_goods_num
        c.c_goods_num = num + 1
    # 存储购物信息
    c.c_user = user
    c.c_goods = goods
    c.save()
    return JsonResponse({'msg': '添加成功'})


def changeselect(request):
    cartid = request.GET.get('cartid')
    cartselected = request.GET.get('cartselected')
    # print(cartid)
    # print(cartselected)
    car = Cart.objects.get(pk=cartid)
    car.c_selected = not cartselected
    car.save()

    return JsonResponse({'msg': 'ok'})


# 购物车数量减1
def cartgoodssub(request):
    cartid = request.GET.get('cartid')
    car = Cart.objects.get(pk=cartid)
    num = car.c_goods_num
    if num == 1:
        #  删除此条数据
        car.delete()
    else:
        car.c_goods_num = num - 1
        car.save()

    return JsonResponse({'num': num - 1, 'msg': 'ok'})


# 生成订单
def genorder(request):
    cartids = request.GET.get('cartids')
    # 列表拆分
    cartids = cartids.split('#')
    # print(cartids)

    # 生成订单  将要购买的商品转换到订单表中，生成订单信息，将购买的商品的订单信息关联
    order = Order()
    username = request.session.get('username')
    user = User.objects.get(u_name=username)
    #
    order.o_user = user
    # 定义状态 0，默认生成状态 ， 1 ，已下单未付款 ， 2 已付款  ，3 已付款并已发货....
    order.o_status = 1
    order.save()
    # order 在存储之后就有id了
    for item in cartids:
        car = Cart.objects.get(pk=item)
        #  修改属于那张表
        car.c_belong = True
        car.c_order = order
        car.save()

    return JsonResponse({'msg': 'ok', 'orderid': order.id})


# 支付，相关平台注册开发者账号，配置自己的信息     ping++可以快速集成多种支付
def pay(request, orderid):
    context = {
        "orderid": orderid,
    }
    return render(request, 'axf/order/pay.html', context)

templates/axf/mine/mine.html
{% extends 'axf/main/main.html' %}
{% load staticfiles %}
{% block mainResource %}
    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
    <script src='{% static "mine/js/register.js" %}'></script>
    <script src='{% static "base/js/md5.js" %}'></script>

{% endblock %}
{% block content %}
    <div id="mine">
        <section class="fixed">

            {#      判断登录(图像)    is_login是true或者false，用来判断是否是否有用户名 #}
            {% if is_login %}
                <img id="user_icon" src="{{ usericon }}" alt="">
            {% else %}
                <span class="glyphicon glyphicon-user"></span>
            {% endif %}

            {#     点击登录信息，显示个人信息       #}
            {% if is_login %}
                <p><a href="{% url 'axf:userInfoMod' %}">{{ username }}</a></p>
            {% else %}
                <p><a href="{% url 'axf:login' %}">{{ username }}</a></p>
            {% endif %}
            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>

            {#        如果未登录，就显示注册按钮   #}
            {% if is_login %}
            {% else %}
                <a id="regis" href="{% url 'axf:register' %}">注册</a>
            {% endif %}

            <p><span class="glyphicon glyphicon-heart"></span>商品收藏</p>
        </section>

        <section class="mine">
            <p>
                <span>我的订单</span><a>查看全部订单&gt;</a>
            </p>
            <nav id="nav">
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-usd"></span></dt>
                                <dd>代付款</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-envelope"></span></dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </nav>


            <menu>
                <ul>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                                <dd>积分商城</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-import"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                                <dd>客服/反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a>
                            <dl>
                                <dt><span class="glyphicon glyphicon-asterisk"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </menu>
            {#  如果登录，显示有登录页面，反之无      #}
            {% if is_login %}
                <p><a href="{% url 'axf:logout' %}">退出当前账号</a></p>
            {% endif %}

        </section>
    </div>


{% endblock %}